name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
	assign:
    	runs-on: ubuntu-latest
    	steps:
			- name: main
				if: ${{ startsWith(github.event.workflow_run.head_commit.message, "release") }}
				run: npm version patch && npm publish --provenance --access public
				env:
					NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}